USE BD_SPIRITUAL_ART
--PROCEDIMIENTOS ALMACENADOS SPIRITUAL ART

ALTER PROCEDURE SP_REGISTRAR_ARTISTA
@NOMBRE_ARTISTA VARCHAR(50),
@PRIMER_APELLIDO_ARTISTA VARCHAR(50),
@SEGUNDO_APELLIDO_ARTISTA VARCHAR(50),
@TELEFONO VARCHAR(30),
@CORREO VARCHAR(40),
@PAIS VARCHAR(30),
@CIUDAD VARCHAR(30),
@LOCALIDAD VARCHAR(50),
@DIRECCION VARCHAR(50),
@FK_TIPO_PLAN INT,
@CLAVE INT,
@ESTADO BIT,
@IMAGEN VARCHAR(MAX)
AS
BEGIN

SET @CLAVE = ABS(CHECKSUM(NEWID()))% 900000
SET @ESTADO = 1
INSERT INTO REGISTRO_ARTISTA(NOMBRE_ARTISTA,PRIMER_APELLIDO_ARTISTA,SEGUNDO_APELLIDO_ARTISTA,TELEFONO,CORREO,PAIS,CIUDAD,LOCALIDAD,DIRECCION,CLAVE,FK_TIPO_PLAN,ESTADO,IMAGEN)
VALUES(@NOMBRE_ARTISTA,@PRIMER_APELLIDO_ARTISTA,@SEGUNDO_APELLIDO_ARTISTA,@TELEFONO,@CORREO,@PAIS,@CIUDAD,@LOCALIDAD,@DIRECCION,@CLAVE,@FK_TIPO_PLAN,@ESTADO,@IMAGEN)
END

EXEC SP_REGISTRAR_ARTISTA 'Luisa','López','Toro','3197564392','lufelopez223@outlook.com','Colombia','Medellín','Antioquia','carrera 80',3,''