CREATE DATABASE BD_SPIRITUAL_ART
USE BD_SPIRITUAL_ART

--TABLA ARTISTA
alter table REGISTRO_ARTISTA add ESTADO BIT
alter table REGISTRO_ARTISTA add IMAGEN VARCHAR(MAX)
CREATE TABLE REGISTRO_ARTISTA(
PK_ID_ARTISTA INT PRIMARY KEY IDENTITY,
NOMBRE_ARTISTA VARCHAR(50),
PRIMER_APELLIDO_ARTISTA VARCHAR(50),
SEGUNDO_APELLIDO_ARTISTA VARCHAR(50),
TELEFONO VARCHAR(30),
CORREO VARCHAR(40),
PAIS VARCHAR(30),
CIUDAD VARCHAR(30),
LOCALIDAD VARCHAR(50),
DIRECCION VARCHAR(50),
CLAVE INT,
FK_TIPO_PLAN INT REFERENCES TIPO_PLAN(PK_ID_TIPO_PLAN)
)

DECLARE @CLAVE INT
SET @CLAVE = ABS(CHECKSUM(NEWID()))% 900000

INSERT INTO REGISTRO_ARTISTA(NOMBRE_ARTISTA,PRIMER_APELLIDO_ARTISTA,SEGUNDO_APELLIDO_ARTISTA,TELEFONO,CORREO,PAIS,CIUDAD,LOCALIDAD,DIRECCION,CLAVE,FK_TIPO_PLAN)
VALUES('Luisa','López','Toro','3197564392','lufelopez223@outlook.com','Colombia','Medellín','Antioquia','carrera 80',@CLAVE,3)

SELECT * FROM REGISTRO_ARTISTA 
delete REGISTRO_ARTISTA where PK_ID_ARTISTA = 1050
--TABLA PLAN
DELETE TIPO_PLAN
ALTER TABLE TIPO_PLAN ADD DESCRIPCION_CANTIDAD_OBRAS VARCHAR(MAX)
ALTER TABLE TIPO_PLAN ADD DESCRIPCION_VISIBILIDAD VARCHAR(MAX)
ALTER TABLE TIPO_PLAN ADD DESCRIPCION_BUSQUEDA VARCHAR(MAX)
ALTER TABLE TIPO_PLAN ADD DESCRIPCION_TIEMPO_PLAN VARCHAR(MAX)

CREATE TABLE TIPO_PLAN(
PK_ID_TIPO_PLAN INT PRIMARY KEY IDENTITY,
NOMBRE_PLAN VARCHAR(20),
PRECIO FLOAT
)

INSERT INTO TIPO_PLAN(NOMBRE_PLAN,PRECIO,DESCRIPCION_CANTIDAD_OBRAS,DESCRIPCION_VISIBILIDAD,DESCRIPCION_BUSQUEDA,DESCRIPCION_TIEMPO_PLAN) VALUES('Básico',30000,'Exposición de hasta 15 obras','Visibilidad intermedia','Prioridad intermedia en búsquedas de tus porductos y obras','6 meses')
INSERT INTO TIPO_PLAN(NOMBRE_PLAN,PRECIO,DESCRIPCION_CANTIDAD_OBRAS,DESCRIPCION_VISIBILIDAD,DESCRIPCION_BUSQUEDA,DESCRIPCION_TIEMPO_PLAN) VALUES('Premium',90000,'Exposición de hasta 30 obras','Visibilidad con preferencia','Prioridad en búsquedas de tus porductos y obras','1 año')
INSERT INTO TIPO_PLAN(NOMBRE_PLAN,PRECIO,DESCRIPCION_CANTIDAD_OBRAS,DESCRIPCION_VISIBILIDAD,DESCRIPCION_BUSQUEDA,DESCRIPCION_TIEMPO_PLAN) VALUES('Gratuito',0,'Exposición de hasta 7 obras','','','2 meses')

SELECT * FROM TIPO_PLAN

--TABLA PRODUCTOS
CREATE TABLE PRODUCTO
(
PK_ID_PRODUCTO INT PRIMARY KEY IDENTITY,
NOMBRE_PRODUCTO VARCHAR(50),
PRECIO FLOAT,
DESCRIPCION VARCHAR(200),
CANTIDAD INT,
ESTADO BIT,
IMAGEN_PRODUCTO VARCHAR(MAX),
FK_CATEGORIA INT REFERENCES CATEGORIA(PK_ID_CATEGORIA),
FK_ARTISTA INT REFERENCES REGISTRO_ARTISTA(PK_ID_ARTISTA)
)

select * from PRODUCTO
--TABLA CATEGORIAS
CREATE TABLE CATEGORIA
(
PK_ID_CATEGORIA INT PRIMARY KEY IDENTITY,
NOMBRE_CATEGORIA VARCHAR(100)

)
select * from CATEGORIA
delete CATEGORIA
insert into CATEGORIA (NOMBRE_CATEGORIA) values('Dibujo a lápiz')
insert into CATEGORIA (NOMBRE_CATEGORIA) values('Pintura')
insert into CATEGORIA (NOMBRE_CATEGORIA) values('Fotografía')
insert into CATEGORIA (NOMBRE_CATEGORIA) values('Arte Moderna')
insert into CATEGORIA (NOMBRE_CATEGORIA) values('Escultura')
--TABLA CLIENTE

--TABLA USUARIO-INFORMACION