//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationSpiritualArt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_PLAN()
        {
            this.REGISTRO_ARTISTA = new HashSet<REGISTRO_ARTISTA>();
        }
    
        public int PK_ID_TIPO_PLAN { get; set; }
        public string NOMBRE_PLAN { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public string DESCRIPCION_CANTIDAD_OBRAS { get; set; }
        public string DESCRIPCION_VISIBILIDAD { get; set; }
        public string DESCRIPCION_BUSQUEDA { get; set; }
        public string DESCRIPCION_TIEMPO_PLAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRO_ARTISTA> REGISTRO_ARTISTA { get; set; }
    }
}
